name: C Build Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GCC and Make
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build the Program
        run: make

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v3
        with:
          name: myprogram
          path: ./myprogram
